import { tool as createTool } from "ai";
import { JSONSchema7 } from "json-schema";
import { jsonSchemaToZod } from "lib/json-schema-to-zod";
import {
  semanticSearch,
  type SearchResult,
} from "lib/vector-search/vector-search-service";
import logger from "logger";
import { safe } from "ts-safe";

const rememberContextSchema: JSONSchema7 = {
  type: "object",
  properties: {
    query: {
      type: "string",
      description:
        "The search query to find relevant context from past conversations",
    },
    limit: {
      type: "number",
      description: "Maximum number of relevant messages to retrieve",
      default: 5,
      minimum: 1,
      maximum: 20,
    },
    scoreThreshold: {
      type: "number",
      description: "Minimum relevance score threshold (0-1)",
      default: 0.7,
      minimum: 0,
      maximum: 1,
    },
    threadId: {
      type: "string",
      description:
        "Optional thread ID to prioritize context from current thread",
    },
    userId: {
      type: "string",
      description:
        "User ID for security filtering (required for proper results)",
    },
  },
  required: ["query", "userId"],
  additionalProperties: false,
};

export interface RememberContextResult {
  results: Array<{
    id: string | number;
    score: number;
    content: string;
    role?: string;
    source: "memory" | "knowledge" | "documents"; // Indicates if from conversation memory, uploaded knowledge base, or autogenerated documents
    threadId?: string;
    messageId?: string;
    createdAt?: string;
    // Knowledge base specific fields
    knowledgeBaseId?: string;
    knowledgeBaseName?: string;
    fileName?: string;
  }>;
  count: number;
  query: string;
  elapsedMs: number;
}

/**
 * Remember Context Tool
 *
 * Searches and retrieves relevant context from past conversations to enhance responses.
 * Uses vector semantic search to find the most relevant previous messages.
 */
export const rememberContextTool = createTool({
  description:
    "Search and retrieve relevant context from past conversations, uploaded knowledge bases, and autogenerated documents to enhance responses. Uses semantic vector search to find the most relevant content from memory, knowledge bases, and documents based on the query. This helps maintain conversation continuity and provide personalized responses.",
  inputSchema: jsonSchemaToZod(rememberContextSchema),
  execute: async (params) => {
    return safe(async () => {
      const { query, limit = 5, scoreThreshold = 0.7, threadId } = params;
      // Get userId from params - REQUIRED for security isolation
      const userId = (params as any).userId as string | undefined;

      if (!query || query.trim().length < 3) {
        return {
          isError: true,
          error: "Query must be at least 3 characters long",
          results: [],
          count: 0,
          query,
          elapsedMs: 0,
        };
      }

      // Check if Qdrant is configured
      if (!process.env.QDRANT_URL) {
        logger.warn("[RememberContext] Qdrant not configured, skipping search");
        return {
          isError: true,
          error: "Vector search not configured",
          results: [],
          count: 0,
          query,
          elapsedMs: 0,
        };
      }

      const start = performance.now();

      // SECURITY: Require userId for proper data isolation
      if (!userId) {
        logger.error("[RememberContext] userId is required but not provided");
        return {
          isError: true,
          error: "userId is required for secure context retrieval",
          results: [],
          count: 0,
          query,
          elapsedMs: 0,
        };
      }

      try {
        // Use the provided scoreThreshold (default 0.7) - allow lower thresholds for better recall
        const effectiveThreshold = Math.max(0.1, scoreThreshold); // Minimum 0.1 for better recall in semantic search

        logger.info(`[RememberContext] Search params:`, {
          query,
          limit,
          scoreThreshold: effectiveThreshold,
          threadId,
          userId,
        });

        // Search all three collections in parallel: messages (assistant memories), knowledge_base (uploaded files), and documents (autogenerated)
        const [memoryResults, knowledgeResults, documentResults] =
          await Promise.all([
            semanticSearch(query, "messages", {
              limit: limit * 2, // Get more results, then filter
              scoreThreshold: effectiveThreshold,
              filters: {
                userId, // REQUIRED: Filter by user for data isolation
              },
              useCache: true, // Enable cache for performance
            }).catch((error) => {
              logger.error(
                "[RememberContext] Failed to search messages collection:",
                error,
              );
              return [];
            }),
            semanticSearch(query, "knowledge", {
              limit: limit * 2, // Get more results, then filter
              scoreThreshold: effectiveThreshold,
              filters: {
                userId, // REQUIRED: Filter by user for data isolation
              },
              useCache: true, // Enable cache for performance
            }).catch((error) => {
              logger.error(
                "[RememberContext] Failed to search knowledge_base collection:",
                error,
              );
              return [];
            }),
            semanticSearch(query, "documents", {
              limit: limit * 2, // Get more results, then filter
              scoreThreshold: effectiveThreshold,
              filters: {
                userId, // REQUIRED: Filter by user for data isolation
              },
              useCache: true, // Enable cache for performance
            }).catch((error) => {
              logger.error(
                "[RememberContext] Failed to search documents collection:",
                error,
              );
              return [];
            }),
          ]);

        // Log results for debugging
        logger.debug(`[RememberContext] Raw search results:`, {
          memoryCount: memoryResults.length,
          knowledgeCount: knowledgeResults.length,
          documentCount: documentResults.length,
        });

        // Merge results from all three collections
        const allResults: Array<
          SearchResult & { source: "memory" | "knowledge" | "documents" }
        > = [
          ...memoryResults.map((r) => ({ ...r, source: "memory" as const })),
          ...knowledgeResults.map((r) => ({
            ...r,
            source: "knowledge" as const,
          })),
          ...documentResults.map((r) => ({
            ...r,
            source: "documents" as const,
          })),
        ];

        // Sort with priority: knowledge base first, then by score
        // Priority order: knowledge > documents > memory
        const sourcePriority = {
          knowledge: 3,
          documents: 2,
          memory: 1,
        };

        const sortedResults = allResults.sort((a, b) => {
          // First, compare by source priority (knowledge first)
          const priorityDiff =
            sourcePriority[b.source] - sourcePriority[a.source];
          if (priorityDiff !== 0) {
            return priorityDiff;
          }
          // If same source, sort by score (highest first)
          return b.score - a.score;
        });

        // Take top results (knowledge base will be prioritized)
        const finalResults = sortedResults.slice(0, limit);

        logger.info(
          `[RememberContext] Search returned ${finalResults.length} results`,
          {
            memoryCount: memoryResults.length,
            knowledgeCount: knowledgeResults.length,
            documentCount: documentResults.length,
            threshold: effectiveThreshold,
            userId,
          },
        );

        const elapsedMs = Math.round(performance.now() - start);

        // Transform results to a more usable format
        const results = finalResults.map((result) => {
          const payload = result.payload;
          const baseResult = {
            id: result.id,
            score: result.score,
            content: String(payload.content || "").trim(),
            source: result.source,
          };

          if (result.source === "memory") {
            // Memory-specific fields
            return {
              ...baseResult,
              role: String(payload.role || "user"),
              threadId: payload.threadId as string | undefined,
              messageId: payload.messageId as string | undefined,
              createdAt: payload.createdAt as string | undefined,
            };
          } else if (result.source === "knowledge") {
            // Knowledge base-specific fields
            return {
              ...baseResult,
              knowledgeBaseId: payload.knowledgeBaseId as string | undefined,
              knowledgeBaseName: payload.knowledgeBaseName as
                | string
                | undefined,
              fileName: payload.fileName as string | undefined,
              createdAt: payload.createdAt as string | undefined,
            };
          } else {
            // Documents (autogenerated) specific fields
            return {
              ...baseResult,
              fileName: payload.fileName as string | undefined,
              documentType: payload.documentType as string | undefined,
              title: payload.title as string | undefined,
              threadId: payload.threadId as string | undefined,
              createdAt: payload.createdAt as string | undefined,
            };
          }
        });

        logger.info(
          `[RememberContext] Found ${results.length} relevant messages (${elapsedMs}ms)`,
        );

        return {
          results,
          count: results.length,
          query,
          elapsedMs,
        } as RememberContextResult;
      } catch (error: any) {
        const elapsedMs = Math.round(performance.now() - start);
        logger.error("[RememberContext] Search failed:", error);
        return {
          isError: true,
          error: error?.message || "Failed to search memory",
          results: [],
          count: 0,
          query,
          elapsedMs,
        };
      }
    })
      .ifFail((e) => {
        return {
          isError: true,
          error: e.message,
          results: [],
          count: 0,
          query: params.query,
          elapsedMs: 0,
        };
      })
      .unwrap();
  },
});
