import { tool as createTool } from "ai";
import { JSONSchema7 } from "json-schema";
import { jsonSchemaToZod } from "lib/json-schema-to-zod";
import logger from "logger";
import { safe } from "ts-safe";

const rememberContextSchema: JSONSchema7 = {
  type: "object",
  properties: {
    query: {
      type: "string",
      description:
        "The search query to find relevant context from past conversations",
    },
    limit: {
      type: "number",
      description: "Maximum number of relevant messages to retrieve",
      default: 5,
      minimum: 1,
      maximum: 20,
    },
    scoreThreshold: {
      type: "number",
      description: "Minimum relevance score threshold (0-1)",
      default: 0.7,
      minimum: 0,
      maximum: 1,
    },
    threadId: {
      type: "string",
      description:
        "Optional thread ID to prioritize context from current thread",
    },
    userId: {
      type: "string",
      description:
        "User ID for security filtering (required for proper results)",
    },
  },
  required: ["query", "userId"],
  additionalProperties: false,
};

export interface RememberContextResult {
  results: Array<{
    id: string | number;
    score: number;
    content: string;
    role?: string;
    source: "memory" | "knowledge" | "documents";
    threadId?: string;
    messageId?: string;
    createdAt?: string;
    knowledgeBaseId?: string;
    knowledgeBaseName?: string;
    fileName?: string;
  }>;
  count: number;
  query: string;
  elapsedMs: number;
}

/**
 * Remember Context Tool
 *
 * Searches and retrieves relevant context from past conversations to enhance responses.
 * Uses vector semantic search to find the most relevant previous messages.
 *
 * In the desktop app, the actual implementation is in electron/ipc/ai.ts (memory_search tool).
 * This renderer-side tool uses Electron IPC when available.
 */
export const rememberContextTool = createTool({
  description:
    "Search and retrieve relevant context from past conversations, uploaded knowledge bases, and autogenerated documents to enhance responses. Uses semantic vector search to find the most relevant content from memory, knowledge bases, and documents based on the query. This helps maintain conversation continuity and provide personalized responses.",
  inputSchema: jsonSchemaToZod(rememberContextSchema),
  execute: async (params) => {
    return safe(async () => {
      const { query, limit = 5, scoreThreshold = 0.7, threadId } = params;
      const userId = (params as any).userId as string | undefined;

      if (!query || query.trim().length < 3) {
        return {
          isError: true,
          error: "Query must be at least 3 characters long",
          results: [],
          count: 0,
          query,
          elapsedMs: 0,
        };
      }

      const start = performance.now();

      // SECURITY: Require userId for proper data isolation
      if (!userId) {
        logger.error("[RememberContext] userId is required but not provided");
        return {
          isError: true,
          error: "userId is required for secure context retrieval",
          results: [],
          count: 0,
          query,
          elapsedMs: 0,
        };
      }

      try {
        // Check if running in Electron with memory API available
        if (
          typeof window !== "undefined" &&
          (window as any).electron?.memory?.search
        ) {
          logger.info("[RememberContext] Using Electron IPC memory search");

          const effectiveThreshold = Math.max(0.1, scoreThreshold);

          const response = await (window as any).electron.memory.search(query, {
            collections: ["messages", "documents", "knowledge"],
            limit: limit * 2,
            scoreThreshold: effectiveThreshold,
            userId,
            threadId,
          });

          const elapsedMs = response.elapsedMs || Math.round(performance.now() - start);

          // Transform results to expected format
          const results = (response.results || [])
            .slice(0, limit)
            .map((r: any) => ({
              id: r.id,
              score: r.score,
              content: r.content,
              role: r.role,
              source: r.source === "messages" ? "memory" : r.source,
              threadId: r.threadId,
              messageId: r.messageId,
              createdAt: r.createdAt,
            }));

          logger.info(
            `[RememberContext] Found ${results.length} results in ${elapsedMs}ms`
          );

          return {
            results,
            count: results.length,
            query,
            elapsedMs,
          } as RememberContextResult;
        }

        // Fallback: Memory not available in this environment
        logger.warn(
          "[RememberContext] Memory system not available. Use the memory_search tool in the desktop app."
        );
        return {
          isError: true,
          error:
            "Memory search not available in this environment. Please ensure you have an OpenAI API key configured in Settings > Models.",
          results: [],
          count: 0,
          query,
          elapsedMs: Math.round(performance.now() - start),
        };
      } catch (error: any) {
        const elapsedMs = Math.round(performance.now() - start);
        logger.error("[RememberContext] Search failed:", error);
        return {
          isError: true,
          error: error?.message || "Failed to search memory",
          results: [],
          count: 0,
          query,
          elapsedMs,
        };
      }
    })
      .ifFail((e) => {
        return {
          isError: true,
          error: e.message,
          results: [],
          count: 0,
          query: params.query,
          elapsedMs: 0,
        };
      })
      .unwrap();
  },
});
