services:
  shadower:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NO_HTTPS=1
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/shadower
    env_file:
      - ../.env
    dns:
      - 8.8.8.8 # Google's public DNS server
      - 8.8.4.4 # Google's public DNS server
    networks:
      - shadower-networks
    depends_on:
      - postgres
      - redis
      - qdrant
    restart: unless-stopped

  postgres:
    image: postgres:17
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    networks:
      - shadower-networks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - shadower-networks
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - shadower-networks
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  qdrant_data:

networks:
  shadower-networks:
    driver: bridge
